<?php
$data = array (
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '生日礼物',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '生日礼物',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '男朋友',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '17',
    'name' => '男朋友',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '女朋友',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '女朋友',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '老公',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '老公',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '老婆',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '老婆',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '节日礼物',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '节日礼物',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '中秋节',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '中秋节',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '国庆节',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '国庆节',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '感恩节',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '感恩节',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '教室节',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '教室节',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '七夕节',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '7',
    'name' => '七夕节',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '个性定制',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '个性定制',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '香水座',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '香水座',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '钥匙扣',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '8',
    'name' => '钥匙扣',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '台灯',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => '台灯',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '照片定制',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '9',
    'name' => '照片定制',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '围巾、帽子',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '10',
    'name' => '围巾、帽子',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '鲜花',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '鲜花',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '蛋糕',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '蛋糕',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '商务礼物',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '商务礼物',
  ),
);
?>